apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: null
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2
        image: nginx:1.25
        ports:
        - containerPort: 80
